title: "Deterministic Blog"
author: "Mehmet Kutay Bozkurt"
description: "Made with <b style=\"color: #f38ba8;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
google_analytics: G-Z62CEK3M0E
repository: mkutay/mkutay.dev
url: "https://mkutay.dev"

# Layout

# Menu

navigation: # file, url, title
  - {file: "about.md", url: "/about/", title: "About"}
  - {file: "academia.html", url: "/academia/", title: "Academia"}
  - {file: "archive.html", url: "/archive/", title: "Archive"}

external: # for available icons see fontawesome.com/icons
  - {title: "Github", icon: "github", url: "https://github.com/mkutay", include_title: false}
  - {title: "Email Me", icon: "envelope", url: "mailto:hello@mkutay.dev", include_title: false}
  - {title: "Feed", icon: "rss", url: "https://mkutay.dev/feed.xml", include_title: false}
  - {title: "Résumé", icon: "file-pdf", url: "https://mkutay.dev/assets/pdfs/mehmet-kutay-bozkurt.pdf", include_title: true}
  - {title: "Sponsor Me", icon: "heart", url: "https://github.com/sponsors/mkutay?o=esb", include_title: true}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
  - jekyll-feed
  - jekyll-sitemap

include: ["_pages"]
